// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function RunScan(arg1:main.ScanRequest):Promise<main.ScanResponse>;

export function SelectInputFile():Promise<string>;
